services:
  bicep:
    image: guitarrapc/docker-bicep:0.5.6
    entrypoint: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - .:/bicep
      - azure:/root/.azure

volumes:
  azure: {}
